services:
  - type: web
    name: demucs-audio-separator
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
