services:
  - type: web
    name: music3
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    preDeployCommand: apt-get update && apt-get install -y ffmpeg
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: YOUTUBE_COOKIES
        value: "<cookies.txt 內容，單行格式>"
      - key: PROXY_URL
        value: "http://your_proxy_ip:port"  #
